version: 2

models:

    - name: sales
      description : all the columns and KPI related to sales.
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description : FK - identifier of the sales orders number.
            tests : 
            - not_null 

          - name: products_id
            description : FK - identifier of products.
            tests : 
            - not_null

          - name: qty

          - name: turnover
            description : the total amount of sales you make over a set period.
            tests : 
            - not_null
          
           

          - name: purchase_cost
            description : refer to cost of Sale.
            tests : 
            - not_null

          - name: margin
            description : the profit (or markup) that a company earns from a sale.